### ISSUE TITLE
Possible vulnerability/bug in isAllowed() function

### ISSUE THREAD

**Issue by rahul-tar** [humaine-anac/environment-orchestrator#1]
The outcome of this vulnerability is that either the agent gets a turn it doesn't deserve or it does not get a turn it deserves. It can happen because variables that are crucial to the environment-orchestrator are being generated/updated outside of it by the agent's code as follows:

1. The function uses the timestamp provided by the agent in its response. This timestamp is generated by the agent code and therefore, it is vulnerable to being inconsistent or manipulated. Inconsistency: Agent code might reside on a different machine and thus time inconsistency might occur as all machines cannot be guaranteed to maintain the same clock ticks. 
Manipulation: The agent's code also might knowingly/unknowingly manipulate the timestamp. 

2. The function also relies on inReplyTo and its sub-attributes such as turnId to make its decision. However, this variable too is subject to the same vulnerability stated before as it resides under the control of the agent's code.

In previous discussions, we had considered maintaining such crucial variables (such as timestamp, turn sequence, etc.) within the environment-orchestrator and not have its onus on the participants. I am wondering if we must go ahead with that.

**Comment by kephart** [comment]
The new rules implemented by Melina, Maira and Jeff avoid all of these problems.
